### ISSUE TITLE
LibAv on Ubuntu/Trusty64 Not Found

### ISSUE THREAD

**Issue by levivoelz** [MTG/essentia#231]
Hello,

I'm trying to build on Ubuntu and have installed dependencies per the installation page, however I'm getting `not found` on two libs. I've tried installing ffmpeg and going that route, but it still isn't working.

Here's what happens after running configure:
```shell
vagrant@vagrant-ubuntu-trusty-64:~/essentia$ ./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp
Setting top to                           : /home/vagrant/essentia 
Setting out to                           : /home/vagrant/essentia/build 
→ configuring the project in /home/vagrant/essentia
→ Building in release mode
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libavcodec' >= 53.25.0     : yes 
Checking for 'libavformat'               : yes 
Checking for 'libavutil'                 : yes 
Checking for 'libavresample'             : not found 
Checking for 'libswresample'             : not found 
Checking for 'samplerate'                : yes 
Checking for 'taglib' >= 1.9             : yes 
Checking for 'yaml-0.1'                  : yes 
Checking for 'fftw3f'                    : yes 
Checking for program python              : /usr/bin/python 
Checking for python version              : (2, 7, 6, 'final', 0) 
Checking for library python2.7 in LIBDIR : yes 
Checking for program /usr/bin/python-config,python2.7-config,python-config-2.7,python2.7m-config : /usr/bin/python-config 
Checking for header Python.h                                                                     : yes 

================================ CONFIGURATION SUMMARY ================================
- fftw detected!
- FFmpeg (or LibAv on debian/ubuntu) seems to be missing.
  The following algorithms will be ignored: ['AudioLoader', 'MonoLoader', 'EqloudLoader', 'EasyLoader', 'MonoWriter', 'AudioWriter']

- libsamplerate (SRC) detected!
  The following algorithms will be included: ['Resample']

- TagLib detected!
  The following algorithms will be included: ['MetadataReader']

- libyaml detected!
  The following algorithms will be included: ['YamlInput', 'YamlOutput']

- Essentia is configured without Gaia2.
  The following algorithms will be ignored: ['GaiaTransform']
  Examples requiring Gaia2 will be ignored

- Compiling 23 examples
  standard_beatsmarker, standard_mfcc, standard_onsetrate, standard_pitchyinfft, standard_fadedetection, standard_spectralcontrast, standard_rhythmtransform, streaming_extractor, streaming_extractor_short_sounds, streaming_extractor_music, streaming_beatsmarker, streaming_mfcc, streaming_gfcc, streaming_rhythmextractor_multifeature, streaming_beattracker_multifeature_mirex2013, streaming_onsetrate, streaming_panning, streaming_tuningfrequency, streaming_key, streaming_pitchyinfft, streaming_predominantmelody, streaming_md5, streaming_extractor_freesound
=======================================================================================
'configure' finished successfully (0.627s)
```

**Comment by levivoelz** [comment]
Ok, I was able to install `libavresample` with `sudo apt-get install libavresample-dev`. If I do the same thing with `libswresample-dev`, the package isn't found.

Here is the output now:

```shell
vagrant@vagrant-ubuntu-trusty-64:~/essentia$ ./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp
Setting top to                           : /home/vagrant/essentia 
Setting out to                           : /home/vagrant/essentia/build 
→ configuring the project in /home/vagrant/essentia
→ Building in release mode
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libavcodec' >= 53.25.0     : yes 
Checking for 'libavformat'               : yes 
Checking for 'libavutil'                 : yes 
Checking for 'libavresample'             : yes 
Checking for 'libswresample'             : not found 
Checking for 'samplerate'                : yes 
Checking for 'taglib' >= 1.9             : yes 
Checking for 'yaml-0.1'                  : yes 
Checking for 'fftw3f'                    : yes 
Checking for program python              : /usr/bin/python 
Checking for python version              : (2, 7, 6, 'final', 0) 
Checking for library python2.7 in LIBDIR : yes 
Checking for program /usr/bin/python-config,python2.7-config,python-config-2.7,python2.7m-config : /usr/bin/python-config 
Checking for header Python.h                                                                     : yes 

================================ CONFIGURATION SUMMARY ================================
- fftw detected!
- FFmpeg / libav detected!
- Using LibAV/FFmpeg install with libavresample support
- libsamplerate (SRC) detected!
  The following algorithms will be included: ['MonoLoader', 'Resample', 'AudioWriter', 'EasyLoader', 'MonoWriter', 'EqloudLoader', 'AudioLoader']

- TagLib detected!
  The following algorithms will be included: ['MetadataReader']

- libyaml detected!
  The following algorithms will be included: ['YamlInput', 'YamlOutput']

- Essentia is configured without Gaia2.
  The following algorithms will be ignored: ['GaiaTransform']
  Examples requiring Gaia2 will be ignored

- Compiling 23 examples
  standard_beatsmarker, standard_mfcc, standard_onsetrate, standard_pitchyinfft, standard_fadedetection, standard_spectralcontrast, standard_rhythmtransform, streaming_extractor, streaming_extractor_short_sounds, streaming_extractor_music, streaming_beatsmarker, streaming_mfcc, streaming_gfcc, streaming_rhythmextractor_multifeature, streaming_beattracker_multifeature_mirex2013, streaming_onsetrate, streaming_panning, streaming_tuningfrequency, streaming_key, streaming_pitchyinfft, streaming_predominantmelody, streaming_md5, streaming_extractor_freesound
=======================================================================================
'configure' finished successfully (0.420s)
```

Also, I am getting a build failure error when running `./waf` after configuring.

```shell
vagrant@vagrant-ubuntu-trusty-64:~/essentia$ ./waf
Waf: Entering directory `/home/vagrant/essentia/build'
→ building from /home/vagrant/essentia
→ building from /home/vagrant/essentia/src
Building all the algorithms
Ignoring the following algorithms: GaiaTransform
→ building from /home/vagrant/essentia/src/examples
→ building from /home/vagrant/essentia/src/python
[  1/323] cxx: src/essentia/algorithm.cpp -> build/src/essentia/algorithm.cpp.1.o
[  2/323] cxx: src/essentia/configurable.cpp -> build/src/essentia/configurable.cpp.1.o
[  3/323] cxx: src/essentia/connector.cpp -> build/src/essentia/connector.cpp.1.o
[  4/323] cxx: src/essentia/debugging.cpp -> build/src/essentia/debugging.cpp.1.o
[  5/323] cxx: src/essentia/essentia.cpp -> build/src/essentia/essentia.cpp.1.o
[  6/323] cxx: src/essentia/essentiautil.cpp -> build/src/essentia/essentiautil.cpp.1.o
[  7/323] cxx: src/essentia/parameter.cpp -> build/src/essentia/parameter.cpp.1.o
[  8/323] cxx: src/essentia/pool.cpp -> build/src/essentia/pool.cpp.1.o
[  9/323] cxx: src/essentia/range.cpp -> build/src/essentia/range.cpp.1.o
[ 10/323] cxx: src/essentia/scheduler/network.cpp -> build/src/essentia/scheduler/network.cpp.1.o
[ 11/323] cxx: src/essentia/scheduler/networkparser.cpp -> build/src/essentia/scheduler/networkparser.cpp.1.o
[ 12/323] cxx: src/essentia/streaming/accumulatoralgorithm.cpp -> build/src/essentia/streaming/accumulatoralgorithm.cpp.1.o
[ 13/323] cxx: src/essentia/streaming/algorithms/devnull.cpp -> build/src/essentia/streaming/algorithms/devnull.cpp.1.o
[ 14/323] cxx: src/essentia/streaming/algorithms/poolstorage.cpp -> build/src/essentia/streaming/algorithms/poolstorage.cpp.1.o
[ 15/323] cxx: src/essentia/streaming/sinkbase.cpp -> build/src/essentia/streaming/sinkbase.cpp.1.o
[ 16/323] cxx: src/essentia/streaming/sourcebase.cpp -> build/src/essentia/streaming/sourcebase.cpp.1.o
[ 17/323] cxx: src/essentia/streaming/streamingalgorithm.cpp -> build/src/essentia/streaming/streamingalgorithm.cpp.1.o
[ 18/323] cxx: src/essentia/streaming/streamingalgorithmcomposite.cpp -> build/src/essentia/streaming/streamingalgorithmcomposite.cpp.1.o
[ 19/323] cxx: src/essentia/streaming/streamingalgorithmwrapper.cpp -> build/src/essentia/streaming/streamingalgorithmwrapper.cpp.1.o
[ 20/323] cxx: src/essentia/stringutil.cpp -> build/src/essentia/stringutil.cpp.1.o
[ 21/323] cxx: src/essentia/utils/asciidag.cpp -> build/src/essentia/utils/asciidag.cpp.1.o
[ 22/323] cxx: src/essentia/utils/asciidagparser.cpp -> build/src/essentia/utils/asciidagparser.cpp.1.o
[ 23/323] cxx: src/essentia/utils/audiocontext.cpp -> build/src/essentia/utils/audiocontext.cpp.1.o
../src/essentia/utils/audiocontext.cpp: In member function ‘void essentia::AudioContext::encodePacket(int)’:
../src/essentia/utils/audiocontext.cpp:349:26: error: ‘av_frame_alloc’ was not declared in this scope
   frame = av_frame_alloc();  
                          ^
../src/essentia/utils/audiocontext.cpp:386:23: error: ‘av_frame_free’ was not declared in this scope
   av_frame_free(&frame);
                       ^
Waf: Leaving directory `/home/vagrant/essentia/build'
Build failed
 -> task in 'essentia' failed (exit status 1): 
	{task 140081112082576: cxx audiocontext.cpp -> audiocontext.cpp.1.o}
['/usr/bin/g++', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-pthread', '-I/home/vagrant/essentia/build/src', '-I/home/vagrant/essentia/src', '-I/home/vagrant/essentia/build/src/essentia', '-I/home/vagrant/essentia/src/essentia', '-I/home/vagrant/essentia/build/src/essentia/scheduler', '-I/home/vagrant/essentia/src/essentia/scheduler', '-I/home/vagrant/essentia/build/src/essentia/streaming', '-I/home/vagrant/essentia/src/essentia/streaming', '-I/home/vagrant/essentia/build/src/essentia/streaming/algorithms', '-I/home/vagrant/essentia/src/essentia/streaming/algorithms', '-I/home/vagrant/essentia/build/src/essentia/utils', '-I/home/vagrant/essentia/src/essentia/utils', '-I/home/vagrant/essentia/build/src/3rdparty', '-I/home/vagrant/essentia/src/3rdparty', '-I/home/vagrant/essentia/build/src/3rdparty/vamp-plugin-sdk-2.4', '-I/home/vagrant/essentia/src/3rdparty/vamp-plugin-sdk-2.4', '-I/usr/include/taglib', '-DHAVE_AVCODEC=1', '-DHAVE_AVFORMAT=1', '-DHAVE_AVUTIL=1', '-DHAVE_AVRESAMPLE=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_TAGLIB=1', '-DHAVE_YAML=1', '-DHAVE_FFTW=1', '-D__STDC_CONSTANT_MACROS', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYTHON_H=1', '../src/essentia/utils/audiocontext.cpp', '-c', '-o', 'src/essentia/utils/audiocontext.cpp.1.o']
```

Any insight is greatly appreciated!

Cheers-
Levi

**Comment by umezo** [comment]
I dont know why your way does not work ,
but I installed essentia to my ubuntu by compiling ffmpeg from source code and it works.

this is my ffmpeg configure option
```
./configure --enable-avresample --enable-shared --enable-gpl --enable-version3 --enable-nonfree --enable-postproc --enable-libfaac --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libxvid --enable-x11grab --enable-libmp3lame --enable-libvpx --enable-pic
```


OS info
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"
```

Essentia build git hash is 154728cb07fef5fa066a20a917fb90fab563df39

**Comment by dbogdanov** [comment]
You'll need a newer lbav If you are building a master branch. Try installing from [utopic](http://packages.ubuntu.com/search?keywords=libavformat-dev) repository

**Comment by levivoelz** [comment]
K. Thanks guys, I'll give it a shot.

**Comment by jenmadtu** [comment]
I am having the exact same as levivoelz problem on ubuntu 14.04. did git clone on master branch version 2.0.1

as **umezo** suggested i installed ffmpeg but with  

    ./configure --enable-gpl --enable-libfaac --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librtmp --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-nonfree --enable-version3

but i still get the same message 

>Checking for 'libswresample'             : not found 

Furthermore as **dbogdanov** suggested i installed using dpkg -i

http://packages.ubuntu.com/trusty/libavformat-dev

but the code ./way still fails at 

>[ 23/323] cxx: src/essentia/utils/audiocontext.cpp -> build/src/essentia/utils/audiocontext.cpp.1.o
>../src/essentia/utils/audiocontext.cpp: In member function ‘void >essentia::AudioContext::encodePacket(int)’:
>../src/essentia/utils/audiocontext.cpp:349:26: error: ‘av_frame_alloc’ was not declared in this scope
>  frame = av_frame_alloc();  
>                          ^
>../src/essentia/utils/audiocontext.cpp:386:23: error: ‘av_frame_free’ was not declared in this scope
>   av_frame_free(&frame);
>                       ^
>Waf: Leaving directory `/root/downloads/essentia/build'
>Build failed

any suggestions?

**Comment by dbogdanov** [comment]
Make sure you've also updated libavutil-dev

Btw, you can add trusty's repositories to apt-get sources and use it instead of dpkg

**Comment by dbogdanov** [comment]
No need to build libav from source if you can use packages from trusty

@jenmadtu It seems you've installed a package from trusty instead of utopic.

Master branch contains a refactor to make compilation work for 14.10, but this breaks compilation 14.04

**Comment by jenmadtu** [comment]
you suggest to update libavutil-dev from utopic but you write to use libav from trusty?

I dont understand what you mean by "Master branch contains a refactor to make compilation work for 14.10, but this breaks compilation 14.04" you mean i cant compile essentia on ubuntu 14.04? only on 14.10? which version of essentia will work on ubuntu 14.04?

**Comment by jenmadtu** [comment]
after come reconfig i have sorted the issue with the utopic packages added to sources.list.

Thank you :)
