### ISSUE TITLE
Doesn't compile with gcc 6.2

### ISSUE THREAD

**Issue by alastair** [MTG/essentia#480]
```
alastair@mahler:~/code/essentia$ g++ --version
g++ (Ubuntu 6.2.0-5ubuntu11) 6.2.0 20160927
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
In file included from ../src/algorithms/essentia_algorithms_reg.cpp:102:0:
/home/alastair/code/essentia/src/algorithms/rhythm/tempotapdegara.h:68:41: error: ‘constexpr’ needed for in-class initialization of static data member ‘const Real essentia::standard::TempoTapDegara::_frameDurationODF’ of non-integral type [-fpermissive]
   static const Real _frameDurationODF = 5.944308390022676;
                                         ^~~~~~~~~~~~~~~~~
/home/alastair/code/essentia/src/algorithms/rhythm/tempotapdegara.h:95:30: error: ‘constexpr’ needed for in-class initialization of static data member ‘const Real essentia::standard::TempoTapDegara::_alpha’ of non-integral type [-fpermissive]
   static const Real _alpha = 0.5; // decoding weighting parameter
                              ^~~
/home/alastair/code/essentia/src/algorithms/rhythm/tempotapdegara.h:96:34: error: ‘constexpr’ needed for in-class initialization of static data member ‘const Real essentia::standard::TempoTapDegara::_sigma_ibi’ of non-integral type [-fpermissive]
   static const Real _sigma_ibi = 0.025; // std of the inter-beat interval pdf,
                                  ^~~~~
In file included from ../src/algorithms/essentia_algorithms_reg.cpp:201:0:
/home/alastair/code/essentia/src/algorithms/rhythm/tempotapmaxagreement.h:56:36: error: ‘constexpr’ needed for in-class initialization of static data member ‘const Real essentia::standard::TempoTapMaxAgreement::_minTickTime’ of non-integral type [-fpermissive]
   static const Real _minTickTime = 5.;  // ignore peaks before this time [s]
                                    ^~
/home/alastair/code/essentia/src/algorithms/rhythm/tempotapmaxagreement.h:65:39: error: ‘constexpr’ needed for in-class initialization of static data member ‘const Real essentia::standard::TempoTapMaxAgreement::_phaseThreshold’ of non-integral type [-fpermissive]
   static const Real _phaseThreshold = 0.175; // size of tolerance window for beat phase
                                       ^~~~~
/home/alastair/code/essentia/src/algorithms/rhythm/tempotapmaxagreement.h:66:40: error: ‘constexpr’ needed for in-class initialization of static data member ‘const Real essentia::standard::TempoTapMaxAgreement::_periodThreshold’ of non-integral type [-fpermissive]
   static const Real _periodThreshold = 0.175; // size of tolerance window for beat period
```

**Comment by alastair** [comment]
I think this is because new gcc supports a new C++ standard by default. We should probably specify which standard we target, and we should be able to continue compiling with new compilers (https://github.com/MTG/essentia/issues/468)

**Comment by alastair** [comment]
From https://gcc.gnu.org/gcc-6/changes.html

`The default mode for C++ is now -std=gnu++14 instead of -std=gnu++98.`

**Comment by alastair** [comment]
I just saw https://github.com/MTG/essentia/issues/171, so after pulling this is now fixed.
However, we should probably consider adding a `-std` flag anyway, so leaving the ticket open for now.

**Comment by dbogdanov** [comment]
Duplicate of #466. Keeping open for the ```-std``` flag.

**Comment by dbogdanov** [comment]
The ```-std``` flag was added in 9b00b182f4d10adbc39e97f7087b0602b03d61b9.
