### ISSUE TITLE
I found many, many erros inside the essentia library

### ISSUE THREAD

**Issue by lazumbra** [MTG/essentia#72]
PLEASE How can I fix this error? I really need help. 

../src/essentia/utils/tnt/tnt_stopwatch.h: Na função ‘double TNT::seconds()’:
../src/essentia/utils/tnt/tnt_stopwatch.h:35:40: erro: ‘CLK_TCK’ was not declared in this scope
In file included from ../src/essentia/utils/tnt/tnt.h:57:0,
                 from ../src/essentia/essentiautil.h:27,
                 from ../src/essentia/essentia.h:30,
                 from ../src/essentia/algorithmfactory.h:27,
                 from ../src/essentia/algorithm.cpp:21:
../src/essentia/utils/tnt/tnt_stopwatch.h: Na função ‘double TNT::seconds()’:
../src/essentia/utils/tnt/tnt_stopwatch.h:35:40: erro: ‘CLK_TCK’ was not declared in this scope

**Comment by dbogdanov** [comment]
Should be fixed in newer versions.

**Comment by sildeag** [comment]
Ubuntu 17.04 with latest essentia source code:
./waf run_python_tests
[==========] 131 tests from 16 test cases ran. (332 ms total)
[  PASSED  ] 124 tests.
[  FAILED  ] 7 tests, listed below:
[  FAILED  ] AudioLoader.SimpleLoad
[  FAILED  ] AudioLoader.SampleFormatConversion
[  FAILED  ] Network.SimpleVisibleNetwork
[  FAILED  ] Network.ExecutionNetworkWithComposite
[  FAILED  ] Scheduler.SourceProxyFork
[  FAILED  ] TreeTraversal.DepthFirstMap
[  FAILED  ] TreeTraversal.DepthFirstSearch
 7 FAILED TESTS
The list looks similar, am I missing something?

**Comment by LiaRabot** [comment]
@sildeag Exactly the same problem here, but with Ubuntu 16.10, essentia-2.1_beta.

**Comment by sildeag** [comment]
@LiaRabot my issue was resolved.  Essentia-2.1 works on Ubuntu 17.04 64-bit.  Issue #633 has the solution.
