### ISSUE TITLE
Essentia fails to compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by shubho** [MTG/essentia#83]
When I configure as below 
./waf configure --mode=release --with-python --with-cpptests --with-examples --with-vamp

I get a message that libswresample hash't been found. It looks like there are no packages ffmpeg and/or ffmpeg-devel for Ubuntu 14.04. Then when I try to build it - it fails on  audiocontext.cpp 

with the following message 

/home/shubho/essentia-2.0.1/src/3rdparty/audioconvert.h:55:6: error: use of enum ‘SampleFormat’ without previous declaration
 enum SampleFormat avcodec_get_sample_fmt(const char\* name);

**Comment by dbogdanov** [comment]
Fixed in 2.0 and 2.0.1 branches, or in 2.1 release
